name: PHP

on: [push]

jobs:
    build:
        name: Convjdr PHP

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: "Set up Docker cache"
              id: integ-tests-cache
              uses: actions/cache@v4
              with:
                  path: /tmp/.cache-integ-tests
                  key: integ-tests-${{ hashFiles('**/Dockerfile*', '**/*.lock', '**/package-lock.json', '**/requirements.txt') }}
                  restore-keys: |
                      integ-tests-

            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Cache composer dependencies
              uses: actions/cache@v4
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.4'

            - name: 'Install Symfony CLI'
              run: |
                curl -sS https://get.symfony.com/cli/installer | bash
                mv /home/runner/.symfony5/bin/symfony /usr/local/bin/symfony

            - name: 'Install the project'
              run: |
                make install

            - name: '🚀 Tests'
              run: make test
